//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace godai
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Damage = 0;
            this.Health = 0;
            this.ManaCost = 0;
        }
    
        public int Id { get; set; }
        public int Damage { get; set; }
        public int Health { get; set; }
        public int ManaCost { get; set; }
    
        public virtual CardType Type { get; set; }
    }
}
